[package]
name = "pkgutils"
version = "0.1.1"
build = "build.rs"

[lib]
name = "pkgutils"
path = "src/lib.rs"

[[bin]]
name = "pkg"
path = "src/bin/pkg.rs"

[[bin]]
name = "cook"
path = "src/bin/cook.rs"

[dependencies]
clap = {version = "2.25", default-features = false}
hyper-rustls = "0.6"
libflate = "0.1.4"
liner = "0.1"
pbr = { version = "1.0", git = "https://github.com/ids1024/pb", branch = "duration" }
serde = "1.0"
serde_derive = "1.0"
tar = { git = "https://github.com/redox-os/tar-rs" }
toml = "0.4"
version-compare = "0.0.4"
ion-shell = { git = "https://github.com/redox-os/ion" }
termion = "1.5"

[dependencies.hyper]
version = "0.10"
default-features = false

[dependencies.octavo]
git = "https://github.com/libOctavo/octavo.git"
default-features = false
features = ["digest"]
